version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    networks:
      - jenkins
    volumes:
      - /home/ubuntu/jenkins_data:/var/jenkins_home

networks:
  jenkins:


